apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wgnetworks.zenguard.io
spec:
  scope: Namespaced
  group: zenguard.io
  names:
    kind: WGNetwork
    plural: wgnetworks
    singular: wgnetwork
    shortNames:
      - wgn
      - wgns
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wgclients.zenguard.io
spec:
  scope: Namespaced
  group: zenguard.io
  names:
    kind: WGClient
    plural: wgclients
    singular: wgclient
    shortNames:
      - wgc
      - wgcs
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true